"""
- Beaux Blanchard
- Mission Control LLC
- Token Retrieval

Houses the client keys generated by Lulu. Contains 1 function:

get_token(json=False): Returns a single string by default, the authentication code that all GET requests require.
            If json=True, it will return the entire JSON dictionary that was returned by Lulu.
"""

import requests

SANDBOX = True

if SANDBOX:
    print("***SANDBOX ACTIVE***")
    URLPREFIX = "https://api.sandbox.lulu.com/"

    """SANDBOX CLIENT KEYS"""

    CLIENT_KEY = ""

    CLIENT_SECRET = ""

    BASE64_KEY_SECRET = ""

else:
    URLPREFIX = f"https://api.lulu.com/"

    """CLIENT KEYS"""
    CLIENT_KEY = ""

    # The client secret can be changed on the developer tools website.
    CLIENT_SECRET = ""

    # This is the combined key in base 64. The word "basic" is required prior to the rest of the code.
    BASE64_KEY_SECRET = ""

# The URL to retrieve a OAuth (the communication system) token. Tokens expire after a few minutes.
url = f"{URLPREFIX}auth/realms/glasstree/protocol/openid-connect/token"

# The headers (-H in curl)
headers = {
    "Content-Type": "application/x-www-form-urlencoded",
    # This contains your encoded credentials
    "Authorization": BASE64_KEY_SECRET
}

# The data (-d in curl)
payload = {
    "grant_type": "client_credentials"
}

def get_token(json=False):
    # Retrieve the authentication from Lulu
    token_response = requests.post(url, headers=headers, data=payload)

    # If successful, the response will have status 200.
    if token_response.status_code == 200:
        token_data = token_response.json()
        auth_code = token_data["access_token"]
        if json:
            return token_data
        else:
            return auth_code
    else:

        raise KeyError(f"Failed to get token. Status code: {token_response.status_code}")
